---
version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # restrictive
    - exhaustruct
    - varnamelen
    - nlreturn
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - wsl
    - nakedret
    - err113
    - godox
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - github.com/course-go/todos
            - github.com/testcontainers/testcontainers-go
            - github.com/google/uuid
            - github.com/jackc/pgx/v5
            - github.com/golang-migrate/migrate
            - github.com/go-playground/validator/v10
            - go.opentelemetry.io/otel
            - github.com/prometheus/client_golang
            - github.com/getkin/kin-openapi
            - github.com/google/go-cmp
            - gopkg.in/yaml.v3
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120

issues:
  fix: true

output:
  formats:
    text:
      path: stdout
    tab:
      path: golangci-lint.out
      colors: false
    html:
      path: golangci-lint.out.html
