run:
  timeout: 3m
  tests: false

linters:
  enable-all: true
  disable:
    # restrictive
    - exhaustruct
    - varnamelen
    - nlreturn
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - wsl
    # deprecated
    - execinquery
    - gomnd

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
  depguard:
    rules:
      main:
        list-mode: strict
        files:
           - $all
        allow:
          - $gostd
          - github.com/course-go/todos
          - github.com/google/uuid
          - github.com/jackc/pgx/v5
          - github.com/golang-migrate/migrate/v4
          - github.com/testcontainers/testcontainers-go
          - github.com/go-playground/validator/v10
          - github.com/prometheus/client_golang

  mnd:
    ignored-files:
      - 'main.go'
      - '.+/test/.+.go'

output:
    sort-results: true
    formats:
      - format: colored-line-number
        path: stdout
      - format: colored-line-number
        path: golangci-lint.out
