global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    static_configs:
      - targets:
        - 127.0.0.1:9090
  - job_name: todos
    honor_timestamps: true
    static_configs:
      - targets:
        - api:8080
