service:
  name: todos
  port: 8080
  location: UTC

logging:
  level: info

database:
  protocol: postgres
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  name: todos
  options: sslmode=disable&options=-c%20TimeZone%3DUTC
